version: '3.8'

services:
  database:
    container_name: kupipodariday-database
    image: postgres
    volumes:
      - pgdata:/data/postgres
    networks:
      - internal-network
    restart: always
  backend:
    container_name: kupipodariday-backend
    image: opv1/kupipodariday-backend
    build:
      context: ./backend
    networks:
      - internal-network
      - internet
    ports:
      - '4000:3000'
    env_file:
      - ./backend/.env
    depends_on:
      - database
    restart: always

  frontend:
    container_name: kupipodariday-frontend
    image: opv1/kupipodariday-frontend
    build:
      context: ./frontend
    networks:
      - internal
    ports:
      - '8081:80'
    depends_on:
      - backend
    restart: always

networks:
  internal-network:
    driver: bridge
    internal: true
  internet:
    driver: bridge

volumes:
  pgdata:
