services:
  database:
    container_name: kupipodariday-database
    image: postgres:latest
    networks:
      - internal
    ports:
      - '5432:5432'
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: kupipodariday-backend
    image: opv1/kupipodariday-backend
    build:
      context: ./backend
    networks:
      - internal
    ports:
      - '4000:3000'
    env_file:
      - ./backend/.env
    depends_on:
      - database
    restart: always

  frontend:
    container_name: kupipodariday-frontend
    image: opv1/kupipodariday-frontend
    build:
      context: ./frontend
    networks:
      - external
    ports:
      - '8081:80'
    depends_on:
      - backend
    restart: always

networks:
  internal:
  external:

volumes:
  pgdata:
